version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: servicebuyer_db
    environment:
      POSTGRES_DB: service_buyer
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 197320
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - servicebuyer_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d service_buyer"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: servicebuyer_api
    environment:
      POSTGRES_CONNECTION_STRING: "user=postgres password=197320 dbname=service_buyer sslmode=disable host=postgres port=5432"
      SERVICE_SERVER_PORT: "8080"
      LOG_LEVEL: "debug"
      LOG_TO_CONSOLE: "true"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - servicebuyer_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/swagger/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  servicebuyer_network:
    driver: bridge
